# Generated by Django 3.2.15 on 2022-10-02 16:49

import autoslug.fields
from django.db import migrations
import leads.models_lead
import leads.models_user


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subdomain',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=8, populate_from='name', unique=True, verbose_name=leads.models_user.custom_slugify),
        ),
        migrations.AlterField(
            model_name='leadattribute',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('account', 'lead_type'), verbose_name=leads.models_lead.custom_slugify),
        ),
    ]
