# Generated by Django 3.2.15 on 2022-10-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20221002_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadattribute',
            name='attribute_type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('choices', 'Choices'), ('email', 'Email'), ('integer', 'Integer'), ('phone_number', 'Phone Number'), ('string', 'String')], max_length=50),
        ),
    ]
