# Generated by Django 3.2.15 on 2022-09-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20220913_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadUserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('accountuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.accountuser')),
                ('leads', models.ManyToManyField(blank=True, to='leads.Lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
