# Generated by Django 3.2.15 on 2022-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_account_lead_leadattribute_leadusermap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='business_desc',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='leadattribute',
            name='value',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='leadusermap',
            name='leads',
            field=models.ManyToManyField(blank=True, to='leads.Lead'),
        ),
    ]
