# Generated by Django 3.2.15 on 2022-09-21 19:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadusermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subdomain',
            field=autoslug.fields.AutoSlugField(default='anas', editable=False, max_length=8, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
