# Generated by Django 3.2.15 on 2022-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20220907_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='data',
            field=models.JSONField(blank=True, default={'main': {}, 'post': {}, 'track': {}}, null=True),
        ),
        migrations.AlterField(
            model_name='leadattribute',
            name='attribute_type',
            field=models.CharField(choices=[('email', 'Email'), ('string', 'String'), ('integer', 'Integer'), ('phone_number', 'Phone Number'), ('choices', 'Choices')], max_length=50),
        ),
    ]
