# Generated by Django 3.2.15 on 2022-09-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20220908_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadattribute',
            name='attribute_type',
            field=models.CharField(choices=[('choices', 'Choices'), ('email', 'Email'), ('integer', 'Integer'), ('phone_number', 'Phone Number'), ('string', 'String')], max_length=50),
        ),
    ]
