# Generated by Django 3.2.15 on 2022-12-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20221208_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadattribute',
            name='seq_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
