# Generated by Django 3.2.15 on 2022-12-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_leadattribute_seq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.account'),
        ),
    ]
